### ISSUE TITLE
Add video link on thumbnails

### ISSUE THREAD

**Issue by ianniscamillieri** [TiC-1/week3-project#12]
To not forget it

**Comment by matjack1** [comment]
The link is there, but it's broken :)

You should add the protocol in front of the `www`.

Plus I'd open the link in a new tab. Hint: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/a (look for `target`)

**Comment by spinagiu** [comment]
created 2 pull request related to this
ciao!
